---
title: | 
  | \vspace{5cm} \LARGE{} Consider the Fly
  | \vspace{10cm} \LARGE{}
author: "Brandon Dey"
date: "5/12/2018"
html_document:
    theme: journal
    css: css/style.css
    toc: yes # table of contents
    toc_depth: 2 # only # header and ## smaller header appear in toc
    toc_float: true # make toc float as I scroll
    collapsed: false
---
<br />
<br /> 

## Description {.tabset}

<p class="newspaper">
Describing what a  fly looks like may seem like overkill. But it’s not; you might not even be picturing the same Fly that Your Author has been talking about because there are over 100,000 species. <br />
<br /> 
One (i.e., *moi*) is quickly overwhelmed by all the anatomical minutia and huge intra-order diversity of the members of the taxonomic class to which all true flies belong, Diptera. Plus within this there are another five layers of categorization, or taxa, into which the manifold species of flies might be bucketed and along which they might differ by something as garden variety (to the non-entomologist) as: [example]. On top of all this, the nuance that separates any one fly species from another gets finer and more technical the deeper one steps down on the taxonomic ladder, making the brave lay-descender quite likely to need to reach for a clear entomological guide, pronto. <br />
<br />
Intrepid you proceeds anyway. You’re likely to get turned around real quick if the latinate layering of scientific taxonomy is as new to you as it was Your Author when he set out to write this, when, while he was navigating this taxonomic hierarchy, he discovered, for example, that he had unwittingly confused the subject of this piece, M. domestica, the housefly, for its cousin, Lucilia sericata, the common green bottlefly, whose memorable iridescent metallic green body reminds him of gasoline whorling on water. This confusion was so entrenched in his psyche that he had been erroneously picturing this green-sheened fly every time someone said the word *Housefly*, or simply *Fly*. Turns out that L. sericata and M. domestica don’t even belong to the same family, which more or less justifies a brief physical description of the humble housefly, M. domestica. <br />
<br />
Zooming out. <br />
<br />
Like all members of the class Insecta, the housefly is made up of a head, thorax, abdomen, three pairs of knobby legs studded with bristly hairs, and a set of antennae, and, like all members of the order Diptera, has only one pair of hardy wings to which its whole head was evidently built in service. The head of a housefly resembles the helmet of a modern fighter jet pilot, its huge protruding hemispheric eyes the visor. This makes sense. The housefly is a strong and fast flyer, capable of pulling off advanced high-g aerobatics, including tight curls, on-a-dime zig zags, and looping rolls on a single pair of wings thanks to a duo of sophisticated fist shaped organs on its back known as halteres that, beating back and forth at 200 hertz during flight, function as gyroscopes, gauging the thorax’s rotational movement to help stabilize the fly by rapidly correcting pitch and yaw when, for example, it’s knocked akilter by a gusty vortex of, say, another too-slow Homo sapien swat. <br />
<br />
Zooming in. Close up headshots of the fly are terrifying. The image puts you on another planet, somewhere where the dark forces of the universe spawn robust whiskers. It's somehow exactly what you expect, yet unlike anything you’ve ever seen. That flies zip around our homes and come into contact with us H. sapiens more than most — or all — other insects amps up the alien factor about tenfold for Your Author. 
</p>

## Something after

<p class="newspaper">
Zooming in. Close up headshots of the fly are terrifying. The image puts you on another planet, somewhere where the dark forces of the universe spawn robust whiskers. It's somehow exactly what you expect, yet unlike anything you’ve ever seen. That flies zip around our homes and come into contact with us H. sapiens more than most — or all — other insects amps up the alien factor about tenfold for Your Author. 
</p>
