---
title: | 
  | \vspace{5cm} \LARGE{} Shelby Dey
  | \vspace{10cm} \LARGE{}
subtitle: "To the (Unsolicited) Rescue of Millennials"
author: "Brandon Dey"
date: "5/12/2018"
html_document:
    theme: journal
    css: css/style.css
    toc: yes # table of contents
    toc_depth: 2 # only # header and ## smaller header appear in toc
    toc_float: true # make toc float as I scroll
    collapsed: false
---
<br />
<br /> 
<br />
<br />

## The Wind Up
<p class="newspaper">
  Shelby Dey is a Millennial by virtue of having been born in 1994. But you'd never guess she was a *Millennial*. Her departure from the Millennial mold warrants some attention both to her, and to this "Millennial mold", which appears to be a default definition in narratives around the Internet and in respected print publications^[See Joel Stein's redemptive article, the cover story of TIME in May, 2013 titled, ["Millennials: The ME ME ME Generation. Millennials are lazy, entitled narcissists who still live with their parents. Why they'll save us all"](http://time.com/247/millennials-the-me-me-me-generation/)]. These narratives cast Millennials in characteristically reductive and, typically, unflattering light. It's often the case that these molds bottle our young people up, make them look like entitled brats – conflating the rich with the poor and everyone in between – and presenting them as products of a culture soiled in social media, obvious aberrations from the traditional values of the Good Ol' Days.
<br />
  More ostensible *Millennial* trappings include: unemployment, a fondness for basement dwelling, often sub their mothers' home, overall laziness and lack of work ethic, disbelief in major world religions supplanted by an unshakable faith in the Almighty Self, and gray matter that's been melted by staring at screens too long. Joining these dubious associations are more generalized traits yet: Cloistered narcissism; Endless chasing of YouTube fame with a seriousness similar to that with which Baby Boomers pursued Doctordom; Constant agony over quipping a clever Facebook post – one balanced with calculated amounts of self-affirmation and self-deprecation to amass the most Likes.
<br />
  Our wise elders, the Baby Boomers and our nearest generational neighbors, the Gen X'ers, forecast that America's future with us Millennials at the helm will be a stormy one. One can easily imagine whole neighborhoods of Baby Boomer gray hair and thick spectacles dooming-and-glooming in their rockers over how photo albums of this future will be clogged with selfies, pics whose perspective doesn't extend beyond an arm's reach – unless a Selfie Stick is used.^[Get yours [here.](https://www.amazon.com/s/ref=nb_sb_noss_2?url=search-alias%3Delectronics&field-keywords=selfie+stick)]
<br />
  While not all sociologists, demographers, journalists, parents, grandparents, etc. out there are this reductive, pessimistic, and/or prone to this particular brand of the fallacy of composition, the bottles continue to be used as directional "evidence", revisited when one wishes to say something wholesale about the people born of an entire generation.
<br />
  Shelby Dey resists such bottling. In part because she wouldn't go willingly, and in part because she doesn't exactly fit into these generalized generation-level expectations, a broad-brush outcome openly acknowledged in a 2010 PEW Research Center report, [*Millennials, A Portrait on Generation Next. Confident. Connected. Open to Change.*](http://assets.pewresearch.org/wp-content/uploads/sites/3/2010/10/millennials-confident-connected-open-to-change.pdf) ^["Generational analysis has a long and distinguished place in social science, and we cast our lot with those scholars who believe it is not only possible, but often highly illuminating, to search for the unique and distinctive characteristics of any given age group of Americans. But we also know this is not an exact science. We are mindful that there are as many differences in attitudes, values, behaviors, and lifestyles within a generation as there are between generations. But we believe this reality does not diminish the value of generational analysis; it merely adds to its richness and complexity."] But if someone did figure out a way to summarily can Shelby Dey, and then somehow manage to persuade other Millennials to drink, as a kind of spiritual or character pick-me-up, maybe, just maybe *Millennials* wouldn't get such a bad rap from those born in, say, any other living generation, ever; distinguished research centers included. 
  (FYI, Shelby would be served cold-pressed in a tall mojito glass, sans nauseating umbrella, freshed-up with organic lime, and would be very expensive; top shelf for sure.)
</p>

Page 1

---



<p class="newspaper">
  Shelby has two tattoos: An Old Testament Bible verse, Micah 6:8, inked in blotchy black Hebrew on her left wrist, and a thin Christian cross, also black, that crests the knob of her northern-most vertebrae on the back of her neck. She has caricature-sized eyes that are a kind of swirly blue and widen genially when she talks. Her shoulder-length brown hair is kept in a ponytail most days, muzzling its natural curl – as it was when we recently chatted over coffee at a favorite café of hers, Coffeeville, in Jackson, Wisconsin, just north of Milwaukee. Despite its cheesy name, suggestive of a kind of caffeinated amusement park fanny-packed with overweight coffee tourists, the rustic space might have been an old railroad station at some point. The walls are those of a log cabin. Depression-era coffee grinders older than railroads themselves are showcased down the length of one of them. She wore a light-gray cardigan over a black T-shirt designed and manufactured by a company whose efforts toward social responsibility and sourcing ethics were her litmus test for purchase. A constellation of subtle freckles confetti her forehead, discernible only to those within coffee-drinking distance, which, given that she's a barista, many are. 
  <br /> 
  A 22^[She's 23 now.] year old Family & Human Development major at ASU, barista-ing at Starbucks until graduation, at which point she plans to enter some nonprofit niché (child placement, maybe), and stuck fretting over midterms most days, she says that, at the moment, "She's not an exciting person." Then she launched into what would become approximately 90 minutes of popcorn-style stories of pretty much anything and everything that turned that statement upside down. 
<br />
  The circles in salami freak her out, but not as much as clowns. She won't touch raw chicken when cooking unless she's wearing gloves, but she's trying to get over that. She's not a vegetarian, per se, yet only eats meat (nothing red) when she thinks her body needs the protein. She likes to say that animals are like people and anthropomorphizes her family's golden retriever, Kaya, pretty much every day. She sleeps with the tattered remains of what I'm sure was once an adorable blankie. Routinely breaking into energetic interpretive dance in the living room is totally her thing. She loathes math and yet isn't really an english person either. Beyoncé really is Queen Bee. She owns shocking hot pink Nike running shoes, yet thinks the color pink is gross. When she gets sick, she requires Emgen-C® fizzy tablets – the orange flavor – tissues with the soothing Vicks lotion, lots of the tea that coats your throat, a heating pad, and Netflix. She doesn't get sick very often, but according to WebMd she might have Lyme disease, or maybe benign eccrine spiradenoma, or maybe a super rare skin condition, or maybe just Internet-enabled hypochondria, which the site fittingly calls "Cyberchondria". She recently decided to only buy clothes from companies who source and manufacture their fabrics ethically – fair wages, no sweatshops – so her wardrobe is pretty threadbare at the moment. Her favorite class in college was Food Politics and she found the degree of government involvement in America's food production "disturbing." Obama, his administration, and now Trump and his, do not enjoy favorable approval ratings from Shelby Dey, as she holds many conspiratorial skepticisms of "The Government" and its role in our lives, though doesn't identify with either side of the aisle. She's traced the origins of her taste for pesto and goat cheese, which she enjoys together sometimes and sometimes not ("it just depends") back to her visit to Swaziland when she was 18, a freshly liberated graduate from the tyranny of high school. Her go-to method of marital reprimand is a (soft) flick of her index finger spring-loaded on her thumb, delivered to the part of me nearest her. And afterwards she will always, always, literally without fail – I can't stress this enough – flick herself, just to see how badly she may or may not have hurt me. She also bites in our playful fights, probably too much. Impressively, she's able to apply deodorant one-handed – that is, left pit with left arm, right pit with right arm – leaving me kind of gawking in (possibly misguided) admiration. While this is impressive to watch, admittedly it seems less impressive to merely read about. "Truly, you just have to be there," as Shelby will say.
</p>

Page 2

---

## At Bat

<p class="newspaper">
Shelby projects an aura of friendly exuberance that feels practically intravenous. This is in part due to her irrepressible cheeriness. Really. Even the reportorial tone of this article seems a touch offensive to her songbird nature. Even the prosaic banter of, say, how she has a dentist's appt. on Tuesday is gilded in a melodic rising-and-falling quality that charges her words with energy better fit for song instead of casual chitchat. I wouldn't think it surreal or bizarre or unusual if one day, chatting, her dialogue materialized in a speech bubble suspended against a musical staff that flowed like a ribbon around her, the various music notes bubbling and dancing into sky as she skipped off into a purplish-orange sunset. 
<br />
  Skipping indeed. If you find yourself in a conversation with Shelby Dey, you may also find yourself a step or twelve behind her in said conversation. No fewer than a handful of times a week, I can't help but feel like a spectator to her stream-of-consciousness-esque monologue rather than a participant in an interactive dialogue. This is because she starts a disproportionate share of her stories with "So then!...", a point most listeners would call "the middle." 
<br />
  For example, "So then going to St. Lucia was fun because there were hippos roaming the street at night, yea, it was a fun trip!" Nevermind that up to this point in our conversation she hadn't mentioned this unidentified place called St. Lucia, so I had no backstory. I hadn't even spurred her with a question because I thought we were still talking about the time she went bungee jumping off a large South African cliff. This completely jives with her excitable demeanor. Her stories are kicked off the same way her adventures start: fast-paced and mid-stride. 
<br />
  Her eagerness to finish isn't limited to stories though. She has an infatuation with death that borderline qualifies her for a career as a Grave Digger. This preoccupation with death and her animated verve at once brings Martha Stewart, Edgar Allan Poe, and Tigger of Winnie the Pooh fame to mind. She says, "Because life's too short," like a leathery maxim, unlike, and at odds with, the overt irony of the overdone slogan of that terrible YOLO! meme. On a Saturday afternoon in March we were in the kitchen preparing dinner for friends. Shelby is cooking over the stove. Opening the fridge and scanning the shelves like I hadn't just opened it 45 seconds before when I was just as bored/hungry, behind me, Shelby goes, "I'm really going to miss you when you're gone." She says it all nonchalant and matter-of-factly like she just told me apples are red. I just stop. 
"Gone? Gone where? Where am I going!?" 
<br />
  This middle-of-the-day reminder of the imminence of my fatality is Shelby's way of saying, I love you. It's a compliment. I guess. 
  <br />
  Wondering if how she toes death's line makes her feel like her life is on the clock, one night, I quiz her:
<br />
<br />
"Do you consider yourself an ambitious woman?"
<br />
<br />
"No." 
<br />
<br />
"Why?" I ask.
<br />
<br />
"Because an ambitious woman would want to give you an answer at 9 o'clock at night!"
<br />
<br />
Changing gears in one of the brief lulls in our conversation, I ask open-endedly:
"Anything else you want to add?"
<br />
<br />
She pauses to think, looking off at nothing to her 1 o'clock.
<br />
<br />
"When I was 18, I tried weed," she says somberly.
<br />
<br />
Silence. 
<br />
<br />
More silence.
<br />
<br />
<br />
<br />
  "I'M KIDDING!!!" she blurts at last, face erupting in feigned confession. "I didn't actually."
I didn't think that she did, not that it would have ultimately mattered had she dabbled in dope during her youth. But something about the black and white stoniness of the character I knew her to have belied her claim of punking around in the experimental phase some of us went through when we were "finding ourselves." Shelby did have to "find herself" like the rest of us did – and are doing; it just doesn't seem like it. This has a lot to do with (1) the profuse amount of sympathy she freely spills into the world, (2) her defined character that palpably fills up a room, – as if she stepped out of a Jane Austen novel, a heroine – and (3) how an inordinate share of her stories – and nearly all told about her – have a parable-like quality, usually complete with some moral instruction awaiting those in the audience who've lost their scruples and could thus use a little moral "elevating", as her family says.
<br />
  Raised in Oshkosh, Wisconsin by parents, her father a pastor and her mother, a retired teacher, who strove to cultivate an awareness of global social problems in her and her three sisters, Shelby is keen on being a Global Citizen. It's clear that she thinks treating others across the pond with dignity is just as important as doing so to those stateside. "We grew up with a global mindset. My parents really demonstrated the value to live life beyond yourself." One year for Christmas, for example, the entire family forwent the very McMerican SUV load(s) of presents and instead gifted their money to World Relief, who bought livestock for a village in need. "It made us a part of their story for a while," she says. Nowadays, though she's stateside, she still itches to exercise her rights as a global citizen. Heading back to Africa for either mission or volunteer work remain possibilities. If she did, she'd focus her efforts somewhere outside Heart for Africa, where she volunteered after high school because she says she would want to have a wider impact. And the children, orphaned infants when she was there, probably wouldn't remember her now. In the meantime she supports Priscilla, a 5th-grader from Ghana, through Compassion International, an international humanitarian aid organization that funnels industrialized dollars to impoverished parts of the globe.
</p>

Page 3

---

<p class="newspaper">
Global citizenry is great and all, but problems abound locally too. And the ones important to her haven't escaped her radar, either. Upon her return from Africa, she became a Big Sister to a young girl through Big Brothers Big Sisters of America, a nonprofit that pairs disadvantaged youth with volunteer mentors. Her "little" – as she's called – is from Oshkosh, where Shelby was living at the time of their pairing. For the last 18 months, the span of our marriage so far, however, Shelby has been in Milwaukee and commuting at least once a month, sometimes more, to maintain and cultivate her relationship with her little. 
<br />
One needn't look far and wide in search of the source of this kind of commitment and integrity in Shelby. She saw her dad, Alan Cleveland, Pastor of a non-denominational church in Oshkosh, occasionally dip into the family's private bank account to cover church expenses. This sort of moral and sacrificial imprinting comes through strongly in Shelby, her hand being ever-extended to others as it is. On this point, Susan Cleveland, her mother, describes her as a "woman of rare definition," who, yes, might extend Subway gift cards to the homeless guy on the corner, but nonetheless sweats visible bullets when picking up a new pair of jeans because she doesn't like spending that kind of money.
<br />
  One Thursday night in April, she spent multiple tens of minutes – possibly more than an hour – watching a documentary about Koko the gorilla, who, after learning sign language, could share all her adorable gorilla thoughts and feelings and love and communicative cuteness and erstwhile inexpressible Gorrilla-dentity to humans – especially Shelby.
<br />
<br />
"This is why I love animals!!!!!!!!" (She can speak a ballet of exclamation points into audibility.)
<br />
<br />
"Why?"
<br />
<br />
"They have a mind of their own. I'm going to burst of cuteness.
Koko had this best friend that was a cat. It would come visit during the day. But then it got hit by a truck and Koko went like this," She makes this big frowny face and raises both fists to her eyes, making a throttling motion, the international sign for boo hoo crying. "Uhn. Soooo cute!!!!!"
<br />
<br />
She shares all this in a high, somewhat pained voice, tonally mellow, yet pitched high like she's talking to a new puppy or a wide-eyed child with a large red lollipop. This is just another part of Shelby's package deal: A conversation with her feels physical in that one has to sort of dissolve the sugary coat on her diction. Doing so leaves one with a rare hand-on-your-arm type of feeling. It took me a while to pinpoint what this actually was. 
<br />
It's contagious sympathy. 
<br />
The fleshy, cutaneous sort of sympathy that you can feel in your chest after she breathes it into a room, a conversation, a friendship, a marriage. This feeling is one of the most special of the feelings available to us in our human condition, and, in a culture given to selfie, it feels refreshingly genuine. Shelby is refreshingly genuine, and wholeheartedly so. 
<br />
  Last summer we were driving down a stretch of Wisconsin interstate when we passed a pasture of cows with their heads face planted into earth, vacuuming clumps of grass with their faces, which I don't notice because, you know, it's Wisconsin and cows don't exactly put the "live" in "livestock" for me like they do her. But Shelby goes, "Awwwwww! I loooovvvvee cows. So cute," she says, beaming. 
<br />
<br />
"What's so cute about them?"
<br />
<br />
"They're like people!!" she flutes, voice rising affectionately.
Though she'd play a believable damsel, she's not some babe in the woods, lost and a wandering. The farm in Swaziland had a guard dog. His name was Thor. On a sunny afternoon in September, Thor was hit by a jeep. The jeep skidded to a halt as he lay in the road, frothing at the mouth and shaking when Shelby rushed over to help. "Death wasn't in the air," she said. "It was in my arms laying waste to this poor animal who had become like family to me." 
It's difficult to imagine Shelby on some dusty unnamed African road holding a dying dog with blood splattered on her shirt. "When you're put into a situation like that, you just need to do what you need to do. We're so reliant on so much stuff here. There, you just rise to the occasion; here we call the vet. There's so much specialization. If that happened here I probably would have just called my parents."
<br />
A kind of pride can be heard in her stories of Africa, showcasing the sort of self-reliance that's strengthened when outside known zones of comfort. Indeed, she delayed going down the well-worn highschool-to-college-to-corporate-cubicle-farm path by travelling to the universe's most HIV-fraught country, and she did this at a time when most 18 year-olds were buying posters for their dorms and deciding on the meal plan that would best feed their late-night drunken grumblies.
</p>

Page 4

---

<p class="newspaper">
But that was three years ago. What is she doing to improve social justice now? Has she protested some cause vehemently in the streets, tomahawking in hand her homemade sign with "[DISSENTING OPINIONS!]" while chanting fragmented protests at lines of police? No, she hasn't. Nor does she plan to. Public demonstrations of dissent have a place in the machinery of effecting change, but difference can also be made through quieter, more private methods – methods that preserve social and interpersonal harmony, two essentials for Shelby – and it's these that are among her choicest actions for righting social justice. She models a morally good life by simply living like an intentional embodiment of integrity, equality, compassion, as a woman with a strong, defined character. She doesn't laugh at ribald jokes, for example. A few years ago, we were at my employer's Christmas party, sitting at a table with one of the partners I had interviewed with. The gentleman told a mild yet obviously raunchy joke – I forget the details – and I chuckled along with the rest of partners sitting around the table. When I noticed that Shelby hadn't, I supposed she just didn't get the punch line. After we had gotten in the car to head home, the first thing she asked was, "Why did you laugh? It wasn't funny. When you laugh, all you're doing is encouraging his vulgarity. You're basically agreeing with him." Boy did I suppose wrong! Where others might have let my chuckle slide, excusing it as simply a response in line with expected social decorum, Shelby falls hard and fast, invoking the moral card, which admittedly I'd be better off for playing more myself. "If you can't do the small things, how do you expect to do the big ones?" is what she'll say, echoing her father in situations as these. And she's right, completely. 
<br />
Her tattoo, the one on her wrist, is Hebrew for Micah 6:8. It reads:
<br />
"He has shown you, O mortal, what is good. And what does the Lord require of you? To act justly and to love mercy and to walk humbly with your God."
<br />
 "I've got the 'act justly' part down I think. But I need to work on the others. My head is wired towards more of a 'Is this good for all?' angle. Let's put it this way: If I were a CEO, I wouldn't cut corners and compromise values for profit. We'd go out of business first." She has no intention of becoming a CEO because someone in that position simply could be caught between a rock and a hard place, morality-wise. (She's thinking of Enron and others). The position simply wouldn't be worth the risk of possibly being mired in immorality, no matter how lucrative the bonuses or options carroted on a shiny stick in front of her are. 
 <br />
In the summer of 2013, Robert Smucker arrived in rural Swaziland, a five-hour drive from Johannesburg, South Africa, ready to volunteer at Project Canaan, the 2,500 acre land development project run by a faith-based orphanage called Heart for Africa. The project is aimed at sustainability and allaying absolute poverty in surrounding Swazi. Mr. Smucker was described to me as postured and polished, so it's no surprise that I was also told in the same breath that it didn't take long for superficial snap judgements about him to blow around campus. He's rude, the volunteers were saying. Brusque. He's probably only here as an exercise of good conscience or as a tax write-off, if there is such a thing, they harrumphed. On his first night in town he breezed into the community kitchen, assembled some food without making eye contact with anyone, and promptly exited to his cabin, apparently retiring for the evening. A little later that night, Shelby spotted him on a rocking chair outside his cabin under a blazing white African moon."Here's this guy, he has a family, and he's travelling by himself. Someone should get to know him," she recounts. So she walked over and introduced herself. They hit it off immediately. It turns out that Robert was a Tooling Engineer from Atlanta and had just returned from a trip to Darfur, Sudan on which he was doing relief work for the massive, decade-long genocide that had ravaged the country. Shelby lit up and shared that she'd been interested in doing mission work since she was a little girl. 
<br />
In telling me this, she never suggested how she might have had another option in this situation, in recalibrating her opinion of this stranger; namely not getting to know Robert and just leaving her opinion of him at her initial judgements, superficially unbased and barely skin-deep. I didn't get the impression that she was interested in lopping off whole chunks of his core identity just because a few of the other volunteers had.
<br />
So too, if we're not careful, we risk bottling an entire generation up in the see-through, partially false walls of reductiveness, thus masking from ourselves our own diversity, endless variability of opinion, attitude and belief. And if we're short on compassionate nuance and deep on hasty judgy-ness we just might end up seeing nothing but those selfies. And "life is just too short" for that. 
</p>
